wandb_version: 1

T:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.01
epoch:
  desc: null
  value: 10
architecture:
  desc: null
  value: ResNet
dataset:
  desc: null
  value: cifar10
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724995727
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
